### ISSUE TITLE
Questions about the practical application of Hulk

### ISSUE THREAD

**Issue by Bo396543018** [OpenGVLab/Hulk#1]
Thank you for your great work.
I have a question about practical inference. Is it necessary to infer twice for keypoint, first by detection to crop the human body and then to infer the key points?

**Comment by Cohesion97** [comment]
If the input image contains multiple people, the answer is yes.

Following UniHCP, Hulk is a top-down method for the 2D pose estimation task. Therefore, you need to detect the person first by inferencing Hulk.

**Comment by Bo396543018** [comment]
Get, thank you for your answer.
