### ISSUE TITLE
Num_tokens in det (task 4) weight is incorrect

### ISSUE THREAD

**Issue by vcadillog** [OpenGVLab/Hulk#2]
Thanks for your work, it was an error on my side I accidentally deleted decoder: peddet_cfgs

**Comment by vcadillog** [comment]
UPDATE:
I solved this problem by commenting 3 lines in hulk_decoder.py related to 289_points_3d.npy file [689-691] and loading the task4 model, even tho this is solved, the problem appears to be in configuration file of 3 and 4 even tho are the same task have different models.

**Comment by MssrGArsON** [comment]
> Thanks for your work, it was an error on my side I accidentally deleted decoder: peddet_cfgs

Hi, Victor!

From your comment, I'm assuming you've sorted out that repository. Could you please share with me an example of how to do one specific task (for me it's 'attr: 5'), how to properly initialize model and get predictions for images tensor, if you know, of course?

Thanks in advance!

**Comment by vcadillog** [comment]
Well I have only done detection, keypoint and parsing tasks, I don't know the exact pipeline for task 5, but the steps to reproduce should be like this:
First create a config file with the task you need, then load that config with the core.config Config_Hulk class, then load the model with a create_model inside core.testers.testers, then load the model with torch.load and pass it to Hulk with model.load_state_dict(your_model).
Then it may be a little tricky, because you need to know what preprocessing your task needs to do and pass it to the input, you can reverse engineer it reading the code. For detection it needed a zero tensor of boxes and for keypoint it needed a dict with the index of symetric pairs, and the center and scale of the detection boxes as a top-down method.
I can't help you any further because I don't know exactly how task 5 works, but hope this helps you on how to start diving in the code.

**Comment by MssrGArsON** [comment]
I’m eternally grateful for your help and time you’ve taken! This insight
has been really useful.

Get luck!

**Comment by danielkonecny** [comment]
Hello @vcadillog, I'm trying to get the parsing task working and you're mentioning that you made it work. I was wondering if you'd be so kind and share the code that you have for this task, please. Thanks in advance!
Daniel

**Comment by vcadillog** [comment]
Sorry, just saw your comment @danielkonecny , I uploaded a inference code for parsing, detect, keypoint and caption models.
You can see visit my fork for the code.
