### ISSUE TITLE
How to train&eval hulk without slurm？

### ISSUE THREAD

**Issue by Bo396543018** [OpenGVLab/Hulk#4]
Is there any good way to train or evaluate Hulk without using Slurm?

**Comment by Cohesion97** [comment]
In https://github.com/OpenGVLab/Hulk/blob/main/core/distributed_utils.py#L525-L533, the original code supports torch.distributed init. Create a new train.sh might be enough. You may find this [blog](https://gist.github.com/TengdaHan/1dd10d335c7ca6f13810fff41e809904) helpful.

**Comment by Bo396543018** [comment]
OK, Thank you~
